name: telco-churn-ci-env

channels:
  - defaults

dependencies:
  - python=3.12.7
  - pip
  - pip:
      - mlflow
      - pandas
      - scikit-learn
      - matplotlib
      - seaborn
      - numpy
      - joblib
